  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: webook
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: webook
    template:
      metadata:
        labels:
          app: webook
      spec:
        containers:
          - name: webook
            image: teammeng/webook:v0.0.1
            env:
              - name: PORT
                value: "8080"
            ports:
              - containerPort: 8080
