### post signup
POST http://localhost:8080/users/signup
Content-Type: application/json

{
    "email": "TeamAlice@email.com",
    "password": "Abc123!!!",
    "confirmPassword": "Abc123!!!"
}

### post signup password mismatch
POST http://localhost:8080/users/signup
Content-Type: application/json

{
    "email": "TeamMeng@email.com",
    "password": "Abc123!!!",
    "confirmPassword": "Abc!!!"
}

### post signup invalid email
POST http://localhost:8080/users/signup
Content-Type: application/json

{
    "email": "TeamMeng",
    "password": "Abc123!!!",
    "confirmPassword": "Abc123!!!"
}


### valid login
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "TeamAlice@email.com",
    "password": "Abc123!!!"
}

### invalid login
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "TeamAlice@email.com",
    "password": "Abc122!!!"
}

### profile
GET http://localhost:8080/users/profile
Cookie: mysession=MTc3Nzg2MjUxM3xkc3NWcVFYR1FhcHhOS0VTVTBEN2xWSENJZndyNXYwSjA5OFJDVzM0LWhNWHdIelFvaGdPT3VmQlJVQmJNODAwVTN4S3BEZEJnM0hwNVp3Y3MtbVB1NWxSanlUaDJ0dHZ8UzUeuHDlCSCs-sjKiRgd6hLOA4uzlOtxmQ90eIZGU4M=; Path=/; Expires=Wed, 03 Jun 2026 02:41:53 GMT; Max-Age=2592000

### logout
GET http://localhost:8080/users/logout
Cookie: mysession=MTc3Nzg1NzI2MXw4WlhLNjdZRV9pN0RkT29jMVdZdWlIV3A2X2VaRUVCY0xleWFSZld4MFVIUnhYYXoyaXFQZVNQYjM3Qm9XbHNsQVBBejMzUUJQOFQ4bU9JcVZ4WGZkU2VEWnMzSWE2WXV8kjL46Us8jcEl5qGaslFqv_n3GJQltCU4KVZ50bJmg2w=; Path=/; Expires=Wed, 03 Jun 2026 01:14:21 GMT; Max-Age=2592000


### valid login with JWT
POST http://localhost:8080/users/loginJWT
Content-Type: application/json

{
    "email": "TeamAlice@email.com",
    "password": "Abc123!!!"
}

### profile
GET http://localhost:8080/users/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzgxMTMwMTMsIlVpZCI6MiwiVXNlckFnZW50IjoidnNjb2RlLXJlc3RjbGllbnQifQ.ScOSsP3xH7lUPMOH3A7_kxSWZTHLooFnXzTZ-Lh6H6mdIfV3RpYV24QZqYk4XbUKOgotcuKdHsGCnYb6m_kP8w


### test webook
GET http://live.webook.com/hello
